export type ThemeBase = {
  background: string;
  surface: string;
  editor: string;
  text: string;
  muted: string;
  accent: string;
  success: string;
  danger: string;
  fontFamily: string;
  colorScheme: "light" | "dark";
  fontSizeScale: number;
  letterSpacing: string;
  radius: number;
  shadowStrength: number;
};

export type ThemeTokens = {
  "theme-font-family": string;
  "theme-font-size-scale": string;
  "theme-letter-spacing": string;
  "theme-radius-small": string;
  "theme-radius-medium": string;
  "theme-radius-large": string;
  "app-text": string;
  "app-text-muted": string;
  "app-text-soft": string;
  "app-text-placeholder": string;
  "app-text-disabled": string;
  "app-text-danger": string;
  eyebrow: string;
  "surface-start": string;
  "surface-end": string;
  "surface-glow": string;
  "app-screen-highlight": string;
  "chrome-surface": string;
  "note-surface": string;
  "card-surface": string;
  "menu-surface": string;
  "conflict-surface": string;
  "conflict-card-surface": string;
  "code-surface": string;
  "ghost-surface": string;
  "scrollbar-track": string;
  "scrollbar-thumb": string;
  "scrollbar-thumb-hover": string;
  "primary-surface": string;
  "primary-text": string;
  line: string;
  "line-strong": string;
  "card-border": string;
  "ghost-border": string;
  "conflict-border": string;
  "conflict-card-border": string;
  overlay: string;
  "card-shadow": string;
  "menu-shadow": string;
  "conflict-shadow": string;
  "status-neutral": string;
  "status-neutral-ring": string;
  "status-saved": string;
  "status-saved-ring": string;
  "status-saving": string;
  "status-saving-ring": string;
  "status-offline": string;
  "status-offline-ring": string;
  "status-conflict": string;
  "status-conflict-ring": string;
  "status-loading": string;
  "status-loading-ring": string;
};

export type ThemeOverrides = Partial<ThemeBase>;
